### ISSUE TITLE
`deflistener` does not exist

### ISSUE THREAD

**Issue by gws** [sunng87/diehard#22]
Hello @sunng87, and thank you for your effort on this library!

`deflistener` is [documented](https://sunng87.github.io/diehard/diehard.core.html#var-deflistener) but I can't find it in `diehard.core`.

Steps to reproduce:
```clojure
(ns user
  (:require [diehard.core :refer [deflistener]))

;; ...
;; deflistener does not exist
```

I could be doing something very wrong, but I can't find reference to `deflistener` in the `diehard.core` tests either, so it's possible it got lost in the shuffle in the move to `0.8.0`, based on my very brief look at the commit history.

**Comment by gws** [comment]
Sorry, I see now that this a documentation bug. The documentation hasn't been updated since `0.8.0`, and that threw me off.

**Comment by sunng87** [comment]
Seems github page is out of sync. I suggest to use [cljdoc](https://cljdoc.org/d/diehard/diehard/) . I will update README of diehard for that.
