### ISSUE TITLE
Failsafe's Timeout usage

### ISSUE THREAD

**Issue by jainsahab** [sunng87/diehard#27]
Can we use [Failsafe's Timeout API](https://jodah.net/failsafe/timeout/) through this library? I want to execute an operation and raise a timeout error if it doesn't execute within a given time.

**Comment by jainsahab** [comment]
@sunng87 let me know if you are okay with me raising a pull request for it.

**Comment by sunng87** [comment]
@jainsahab Sorry for late. Pull requests are welcomed!

**Comment by sunng87** [comment]
Fixed in #31
