### ISSUE TITLE
:backoff-ms documentation does not match failsafe docs

### ISSUE THREAD

**Issue by hukka** [sunng87/diehard#29]
The current docs say

> the delay for nth retry will be (max (* initial-delay-ms n) max-delay-ms)

while failsafe says on http://jodah.net/failsafe/javadoc/net/jodah/failsafe/RetryPolicy.html#withBackoff-long-long-java.time.temporal.ChronoUnit-

> Sets the delay between retries, exponentially backing off to the maxDelay and multiplying successive delays by a factor of 2.

so the correct formula would be
`min(max-delay-ms, (initial-delay-ms × 2^(n-1)))`

**Comment by sunng87** [comment]
Thanks! Fixed in 98a0743
