### ISSUE TITLE
Use of getFailure is deprecated in FailSafe

### ISSUE THREAD

**Issue by yenda** [sunng87/diehard#51]
I got the following warning in Eastwood:

Instance method 'public java.lang.Throwable dev.failsafe.event.ExecutionCompletedEvent.getFailure()' is deprecated

according to the javadoc one should use getException instead
https://failsafe.dev/javadoc/core/

**Comment by sunng87** [comment]
Thank you for the information. I will create a fix this weekend.

**Comment by sunng87** [comment]
Released in 0.11.3
